name: tunely_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  hugeicons: ^0.0.11
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  provider: ^6.1.5
  audioplayers: ^6.4.0
  shared_preferences: ^2.3.3
  lottie: ^3.1.3
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
